FROM ubuntu:20.04

RUN apt-get update
RUN apt-get -y install curl software-properties-common

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;
    
# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline

# Intel CPUs amd64, etc
#ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/

# Apple MAC M1 or other ARM systems
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-arm64/
RUN export JAVA_HOME

# Install Python 3.10 and pip
RUN apt-get install -y \
	python3 \
	python3-pip

### Get Pyspark, Pytest, sympy, chispa
RUN pip3 install --upgrade pip setuptools pyspark sympy \
&& pip3 install --upgrade -Iv pytest==6.2.5 chispa==0.8.1

COPY . ./src

WORKDIR "/src"

CMD ["pytest", "test/"]
